# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a0be0258459d25072387639fe9a4c56e7c1e455f3a11d453dd44d4a73b95ef82136738c649c08edff820ba292cb08250d12db47377b99a2234cc31a143a99163

test:
  secret_key_base: 65d8e8b1306454cc60256415c76e2671e067142030c19cf1c51fda8e08fe10d5319950db0dc789a5b81b0b3b180eb52986e40713dffa18c199be07738d8e2d3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
